name: 🧪 Single CUDA Build Test (Python 3.11)

# Test workflow for single CUDA build with virtual environment isolation
# Combines 64 parallel/100GB cache approach with tmpfs virtual environment

on:
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if no changes detected'
        required: false
        default: true
        type: boolean
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'aphrodite/**'
      - 'setup.py'
      - 'pyproject.toml'
      - 'requirements/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - '.github/workflows/single-cuda-build-test.yml'
      - 'kernels/**'

env:
  # Build configuration - OPTIMIZED approach that worked previously
  CMAKE_BUILD_TYPE: Release
  MAX_JOBS: 64  # High parallelism that worked previously
  CCACHE_MAXSIZE: 100G  # Large cache that worked previously
  # Echo Systems configuration
  ECHO_ENABLE_DEEP_TREE: true
  ECHO_ENABLE_VM_DAEMON: true
  APHRODITE_TARGET_DEVICE: cuda

jobs:
  single-cuda-build:
    name: 🏗️ Single CUDA Build Test (Python 3.11)
    runs-on: ubuntu-latest
    timeout-minutes: 900
    strategy:
      fail-fast: false
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧹 Aggressive Disk Space Cleanup
        run: |
          echo "::group::Initial Disk Space"
          df -h
          echo "::endgroup::"
          
          echo "::group::Cleanup System"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "::endgroup::"
          
          echo "::group::Clean Build Artifacts"
          find /tmp -name "*.fatbin.c" -delete 2>/dev/null || true
          find /tmp -name "*.cudafe*" -delete 2>/dev/null || true
          find /tmp -name "tmpxft_*" -delete 2>/dev/null || true
          rm -rf kernels/xqa/cubin/ || true
          find kernels/ -name "*.cubin" -delete 2>/dev/null || true
          find kernels/ -name "*.fatbin" -delete 2>/dev/null || true
          echo "::endgroup::"
          
          echo "::group::Final Disk Space"
          df -h
          echo "::endgroup::"

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 🔧 Setup CUDA 12.4
        run: |
          # Use same CUDA installation approach as main workflow
          cuda_version="12.4"
          cuda_version_dash=$(echo $cuda_version | tr "." "-")
          wget -nv https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-${cuda_version_dash} cuda-nvcc-${cuda_version_dash} cuda-libraries-dev-${cuda_version_dash}
          echo "PATH=/usr/local/cuda-${cuda_version}/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/cuda-${cuda_version}/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: 💾 Cache Build Directory (Large Cache)
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            ~/.cache/pip
            ~/.ccache
          key: single-cuda-cache-${{ hashFiles('setup.py', 'pyproject.toml', 'requirements/**') }}
          restore-keys: |
            single-cuda-cache-

      - name: 🔧 Setup ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache
          ccache --set-config=max_size=$CCACHE_MAXSIZE
          ccache --set-config=compression=true
          ccache --zero-stats
          echo "/usr/lib/ccache" >> $GITHUB_PATH

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if [ -f requirements/common.txt ]; then
            pip install -r requirements/common.txt --timeout 18000
          fi

      - name: 🏗️ Single CUDA Build with High Parallelism + Virtual Environment
        timeout-minutes: 900
        run: |
          echo "::group::Build Configuration"
          echo "Target Device: cuda"
          echo "Python Version: 3.11"
          echo "MAX_JOBS: $MAX_JOBS"
          echo "CCACHE_MAXSIZE: $CCACHE_MAXSIZE"
          echo "CMAKE_BUILD_TYPE: $CMAKE_BUILD_TYPE"
          df -h
          echo "::endgroup::"
          
          # Use the updated build script with virtual environment + high parallelism
          if [ -f ".github/workflows/scripts/build.sh" ]; then
            # Override MAX_JOBS for high parallelism test
            export MAX_JOBS=64
            export NVCC_THREADS=8
            bash .github/workflows/scripts/build.sh 3.11 12.4
          else
            echo "Build script not found, using fallback"
            python setup.py bdist_wheel --dist-dir=dist
          fi
          
          echo "::group::Build Results"
          ls -la dist/ || echo "No dist directory found"
          df -h
          ccache --show-stats
          echo "::endgroup::"

      - name: 🧪 Basic Smoke Tests
        run: |
          echo "::group::Smoke Tests"
          python -c "import aphrodite; print('✅ Aphrodite import successful')"
          echo "::endgroup::"

      - name: 📤 Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: single-cuda-build-artifacts-py311
          path: |
            dist/
            build/
          retention-days: 7
