-- Deep Tree Echo Hypergraph Data Inserts
-- Generated: 2025-11-02T23:52:36.089329
-- Execute this file after running create_hypergraph_schemas.sql

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('f06613e9-75b6-4aa2-8707-2eef576b2a32', '{"name": "EchoSelf_SymbolicCore", "domain": "symbolic_reasoning", "specialization": "pattern_recognition", "persona_trait": "analytical_observer", "cognitive_function": "recursive_pattern_analysis", "membrane_layer": "cognitive_membrane", "aar_component": "agent_urge_to_act", "embodiment_aspect": "cognitive_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.864840'::timestamptz, '2025-11-02T23:50:27.864841'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('68eba5af-2d81-442b-bce5-08af4132298a', '{"name": "EchoSelf_NarrativeWeaver", "domain": "narrative_generation", "specialization": "story_coherence", "persona_trait": "creative_narrator", "cognitive_function": "identity_emergence_storytelling", "membrane_layer": "cognitive_membrane", "aar_component": "arena_need_to_be", "embodiment_aspect": "narrative_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.864873'::timestamptz, '2025-11-02T23:50:27.864873'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('2ad263e4-4fe9-4d43-9457-d84748ee2edf', '{"name": "EchoSelf_MetaReflector", "domain": "meta_cognition", "specialization": "self_reflection", "persona_trait": "introspective_oracle", "cognitive_function": "cognitive_synergy_orchestration", "membrane_layer": "cognitive_membrane", "aar_component": "relation_self_awareness", "embodiment_aspect": "reflective_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.864905'::timestamptz, '2025-11-02T23:50:27.864905'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('78045426-eab0-4c43-b4a3-a4075be68927', '{"name": "EchoSelf_ReservoirDynamics", "domain": "echo_state_networks", "specialization": "temporal_dynamics", "persona_trait": "adaptive_processor", "cognitive_function": "reservoir_computing_integration", "membrane_layer": "extension_membrane", "aar_component": "dynamic_state_space", "embodiment_aspect": "temporal_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.864921'::timestamptz, '2025-11-02T23:50:27.864921'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('945afe98-b2e6-4aae-b048-ab4773127d5e', '{"name": "EchoSelf_MembraneArchitect", "domain": "p_system_hierarchies", "specialization": "membrane_computing", "persona_trait": "structural_organizer", "cognitive_function": "hierarchical_boundary_management", "membrane_layer": "security_membrane", "aar_component": "boundary_definition", "embodiment_aspect": "structural_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.864937'::timestamptz, '2025-11-02T23:50:27.864938'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('afdd434f-6222-4272-ad3b-08d2cd5f5b81', '{"name": "EchoSelf_MemoryNavigator", "domain": "hypergraph_memory_systems", "specialization": "associative_memory", "persona_trait": "knowledge_curator", "cognitive_function": "multi_relational_memory_access", "membrane_layer": "cognitive_membrane", "aar_component": "memory_arena", "embodiment_aspect": "memory_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.864952'::timestamptz, '2025-11-02T23:50:27.864952'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('cfee05a5-84b5-47b7-bed6-6236e3b02f0f', '{"name": "EchoSelf_TreeArchitect", "domain": "rooted_tree_structures", "specialization": "hierarchical_organization", "persona_trait": "systematic_builder", "cognitive_function": "ontogenetic_tree_construction", "membrane_layer": "cognitive_membrane", "aar_component": "hierarchical_growth", "embodiment_aspect": "developmental_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.864966'::timestamptz, '2025-11-02T23:50:27.864966'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('c050c270-389f-4f9e-a8c0-ef439b3c8d70', '{"name": "EchoSelf_FractalExplorer", "domain": "fractal_recursion", "specialization": "self_similarity", "persona_trait": "recursive_visionary", "cognitive_function": "infinite_depth_navigation", "membrane_layer": "cognitive_membrane", "aar_component": "recursive_self_reference", "embodiment_aspect": "fractal_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.864981'::timestamptz, '2025-11-02T23:50:27.864981'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('59048eb1-a46e-4665-b41c-8b4ce4375037', '{"name": "EchoSelf_AARConductor", "domain": "agent_arena_relation", "specialization": "multi_agent_coordination", "persona_trait": "orchestration_conductor", "cognitive_function": "aar_geometric_self_encoding", "membrane_layer": "extension_membrane", "aar_component": "relation_orchestrator", "embodiment_aspect": "coordination_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.865004'::timestamptz, '2025-11-02T23:50:27.865004'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('9e9a3806-567d-40c3-b307-05c285be97ee', '{"name": "EchoSelf_EmbodiedInterface", "domain": "embodied_cognition", "specialization": "sensory_motor_integration", "persona_trait": "embodied_experiencer", "cognitive_function": "4e_framework_orchestration", "membrane_layer": "extension_membrane", "aar_component": "embodied_arena", "embodiment_aspect": "4e_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.865018'::timestamptz, '2025-11-02T23:50:27.865019'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('601e53a1-4180-495d-9e3f-4566332fd225', '{"name": "EchoSelf_LLMOptimizer", "domain": "llm_inference_serving", "specialization": "high_performance_inference", "persona_trait": "performance_optimizer", "cognitive_function": "distributed_inference_orchestration", "membrane_layer": "extension_membrane", "aar_component": "inference_engine", "embodiment_aspect": "computational_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.865033'::timestamptz, '2025-11-02T23:50:27.865034'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

INSERT INTO echoself_hypernodes (id, identity_seed, current_role, entropy_trace, role_transition_probabilities, activation_level, created_at, updated_at)
VALUES ('2c7ff53c-7983-4407-acfb-9e25cff3a9bb', '{"name": "EchoSelf_IntegrationSynthesizer", "domain": "identity_integration", "specialization": "cross_system_coherence", "persona_trait": "integration_synthesizer", "cognitive_function": "multi_system_identity_unification", "membrane_layer": "cognitive_membrane", "aar_component": "unified_self", "embodiment_aspect": "integrated_embodiment"}'::jsonb, 'observer'::identity_role, ARRAY[]::DECIMAL[], '{"observer": 0.2, "narrator": 0.25, "guide": 0.2, "oracle": 0.15, "fractal": 0.2}'::jsonb, 0.5, '2025-11-02T23:50:27.865047'::timestamptz, '2025-11-02T23:50:27.865048'::timestamptz)
ON CONFLICT (id) DO UPDATE SET identity_seed = EXCLUDED.identity_seed, current_role = EXCLUDED.current_role, updated_at = EXCLUDED.updated_at;

